version: "3"
services:
    iperf:
        container_name: iperf
        image: quay.io/janrk/iperf
        restart: always
        ports: 
            - 5201:5201/tcp
            - 5201:5201/udp
        command:
            --server
