version: "3"
services:
    iperf:
        container_name: iperf
        image: quay.io/janrk/iperf
        restart: always
        ports: 
            - 5001:5001/udp
        network_mode: "host"
        command:
            -s -u
